### ISSUE TITLE
Error: Cannot find module './data/female-human-names-en.json'

### ISSUE THREAD

**Issue by direct808** [AlessandroMinoccheri/human-names#3]

**Comment by AlessandroMinoccheri** [comment]
Can you please put more information about this error? When you retrieve this error?

Thanks

**Comment by direct808** [comment]
Hello. Files in the data directory are not listed in the files section of the package.json file. Probably why an error occurs

**Comment by AlessandroMinoccheri** [comment]
Ok. Do you want to make a pull request about it? Or waiting for next release as soon as possible?

**Comment by direct808** [comment]
I can do pull request

**Comment by AlessandroMinoccheri** [comment]
Solved #4 @direct808
